### ISSUE TITLE
Profile Page not updating, even though matches are being logged.

### ISSUE THREAD

**Issue by AiSard** [Razviar/mtga-pro-tracker#118]
Profile Page seems bugged and hasn't updated for two days.
Other parts of the site are logging things as usual (match history, gold/gems, win rate, etc)
Just the profile page has stopped.

**Comment by scottelliott** [comment]
Same. Although, I'm having issues with it not reporting matches, gold, cards, etc. prior to today.

**Comment by Razviar** [comment]
Please provide a link to your profile page

**Comment by apoapostolov** [comment]
I confirm this issue started since yesterday

* Social Feed either doesn't update or updates with a huge delay
* My Matches are updated in real time BUT decks do not appear in My Decks and Social Feed is updated with delay (as mentioned above).

**Comment by Razviar** [comment]
No changes/updates in social service were not implemented, so I have no idea for now what can be causing this. Need to investigate, and it won't be fast. Sorry.

**Comment by scottelliott** [comment]
> Please provide a link to your profile page

Now, the only caveat I can think of is that my profile was created with my real name listed as the **Nickname** which I immediately changed to [Dragosven](https://mtgarena.pro/u/Dragosven).

There are definitely some oddities going on : 

- If you use the aforementioned link, you will note that  **_nothing_** pulls up.

- While logged in, you'll notice that **My Areana** > **My Profile** links to [https://mtgarena.pro/u/](https://mtgarena.pro/u/), **NOT** [https://mtgarena.pro/u/Dragosven](https://mtgarena.pro/u/Dragosven), as you would think it would.

- When you click **My Areana** > **[My Profile](https://mtgarena.pro/u/)**, you see that _**something**_ occurs and you are redirected to [https://mtgarena.pro/u/Dragosven](https://mtgarena.pro/u/Dragosven).

- While this might be expected behavior, the result ( screenshot attached below ) is an unexpected one where my avatar is the correct avatar, but my real name is showing instead of my nickname, the wrong url is displayed under that, and **_nothing_** appears in the main area of the page.

![image](https://user-images.githubusercontent.com/732509/47741793-2cf86600-dc49-11e8-9ff7-e471a9af1b39.png)

**Comment by apoapostolov** [comment]
@Razviar this may be related to the same issue we had with MTGMAD. The site lacks normalization of nicknames used for social feed and people are entering stuff that breaks the site, either initially or after renaming themselves. I think Scott's issue is due to a space.

**Comment by AiSard** [comment]
@Razviar 
> Please provide a link to your profile page

https://mtgarena.pro/u/AiSard/
https://mtgarena.pro/progress/#AiSard
https://mtgarena.pro/matches/#AiSard

As can be seen (I checked on incognito mode just to be sure), Everything in Progress and Matches etc are up to date. It is only the main Profile Page that last updated on the 25th.

I haven't changed my username and no special characters or spaces, so @scottelliott probably has a separate issue. My profile shows up fine, no delays, just not updating period.

**Comment by AiSard** [comment]
Huh, spent some more time and it has somewhat resolved itself(?).

Even though I'd restarted mtgapro.exe to no avail, simply restarting the computer has somewhat allowed the program to update my Profile Page with all the card/gold/wc/etc. progress (except matches). I hibernate often, and rarely restart, if that helps explain things.

Its a bit weird that all the other pages had been up to date except for the Profile Page?... but maybe updates to the Profile Page is being triggered differently than everything else?

*Sorry, going through the history a second time, I realize Progress and Match History, while more up to date than the Profile Page, missed out the matches on the 28/29th (which were non Gaby events), but I'm unsure if that's related to this issue or just the normal desyncing that seems to happen with mtgapro every now and then...

**Comment by AiSard** [comment]
Sorry for the multiple response posts in advance. Hopefully this short recap will help summarize my ramblings.

Profile Page stopped updating since the 25th.
Progress and Match History kept updating until the 27th.
Nothing is logged, including the gem purchase I made on the 28th (just checked the email receipt)
Restarted pc on the 31st which updated cards/gold/gems/wc but not matches, on all pages.
