### ISSUE TITLE
Since last update, get get tracker to work

### ISSUE THREAD

**Issue by Odross** [Razviar/mtga-pro-tracker#364]
Reinstaled many times, always crashes on start up, gets error validating token.
[upload_err_log.txt](https://github.com/Razviar/mtga-pro-tracker/files/2973775/upload_err_log.txt)

**Comment by Aquaman88** [comment]
Hi! Thank you for your log file. For some reasons some users were unable to get app connect because of some SSL protocol discrepancies. We are not sure what exactly helped that time, so cant give you any advice for now. We will investigate this problem. You can try to solve this problem after clicking button "Full reset" in your tracker. Also you should check the valid token in tracker and the name of your account in tracker`s settings. You can also try to remove program manually and then install tracker again. Programm Data directory is at appdata/roaming/mtgaprotracker .
