### ISSUE TITLE
Stats Page doesn't work

### ISSUE THREAD

**Issue by osekaar** [Razviar/mtga-pro-tracker#369]
**Describe the bug**
When i click on my "Stats" page it doesn't show anything. 

**To Reproduce**
1. Go to 'Arena Pro site'
2. Click on 'Stats page in the menu'

**Expected behavior**
To see my statistics

**Screenshots**
![image](https://user-images.githubusercontent.com/48648017/54490856-fbabca00-48b9-11e9-8a63-6c87b7e095e5.png)

**Comment by Aquaman88** [comment]
Hi! Thank you for your message. One of the main reasons of it can be programms in your computer or in your browser (brandmauer, addblock, antivirus etc). If it's just the stats page, then disable your adblocker on that page, or edit the filter to whitelist the file pers_stats.js. This is caused because of an unfortunate file name: https://mtgarena.pro/wp-content/plugins/mtgarenapro/js/pers_stats.js . Adblockers are very sensitive when it comes to filenames and will clobber pretty much any file ending in stats.js.  (c)
