### ISSUE TITLE
My client has stopped syncing since a lot of time ago, despite being updated or being reset

### ISSUE THREAD

**Issue by nikwaralo** [Razviar/mtga-pro-tracker#441]
**Describe the bug**
As in the tile. Run the client (alone, no others trackers), he looks for updates, look at log file and does nothing. Full reset, manual sync, sync old long does not change behavior

**To Reproduce**
Just open it

**Expected behavior**
should upload data so that if I go on my profile on the site I'm able to see progress and matches, but it does nothing

**Screenshots**
-
**Additional context**
-

**Comment by Razviar** [comment]
Is it updated to version v 1.7.9?

**Comment by nikwaralo** [comment]
Absolutely, fully updated

**Comment by Razviar** [comment]
Try to set up date format in tracker settings

**Comment by nikwaralo** [comment]
Hi,
I've set the date format as explained on the website, client confirms that format is correct, but still same behavior (opening old log, reading old log, then goes back to awaiting for updates....)

Still no info from the logs is on my page on MTGApro website

**Comment by Razviar** [comment]
Sorry, in this case I can't provide any help, because we can't replicate the bug. Tracker works fine for the most of users and uploads data correctly. Seems like something specific to your PC.

As measures without guaranteed results I can suggest to create new account on site and inputted new token after reset. Also you may try to reinstall the app. Also, try to run with disabled onscreen overlay and see if it uploads.

**Comment by nikwaralo** [comment]
Well, 
actually it has the same behavior both on my laptop and on my Desktop, so it is definitely not something specific to a PC. I'm not willing to create a new account, I've already reinstalled and reset the app. I've never used overlays, I don't like them.
To me, this is related to my account, but if you can't understand why, I'm gonna have to stop using your app. Unfortunate

**Comment by Razviar** [comment]
Sorry, nothing I have to add
