### ISSUE TITLE
Application hangs with "flicker" when loading this logfile

### ISSUE THREAD

**Issue by Ezelmannen** [Razviar/mtga-pro-tracker#472]
**Describe the bug**
Using the function to "Scan Old Logs" the application processes all my old logs _(even though I don't see any results on the website. . but that's another issue)_ except the attached one which instead starts to "flicker" the buttons "Manual Re-Sync" and "Scan Old Logs"

**To Reproduce**
1. Click on "Scan Old Logs"
2. Select the attached log-file (unzipped of course)

**Expected behavior**
Successful parse of the log

**Screenshots**

**Additional context**
I'm using v1.8.2

[UTC_Log - 7-25-2019 6.06.54 AM - 1.zip](https://github.com/Razviar/mtga-pro-tracker/files/3439357/UTC_Log.-.7-25-2019.6.06.54.AM.-.1.zip)

**Comment by Razviar** [comment]
Thanks, we'll check this log

**Comment by Lucille654** [comment]
Investigation showed that "flicker" happens when you try to upload log generated by MTGA client before latest update (which changed log format). Unfortunately, support of both formats is not going to be implemented. But we will fix this in order to get rid of flicker and show user proper warning message.

**Comment by Ezelmannen** [comment]
Ok. Flicker still occurs in 1.8.3 I noticed. :-)

**Comment by Razviar** [comment]
Just released 1.8.4 fixes this issue
